# Generated by Django 3.2.10 on 2021-12-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='starts',
            new_name='stars',
        ),
    ]
